                                                 
  
                                                         
                                                                           
                                                                      
                                                 
  
                                                
                                                    
                                                    
                                                                                    
                                         
                                                                   
                                                                  
                                
                          
                                                              
                                                

   
                                                     
                                           
                                               
                                                 
                      
   
                                                                           
                                                
                                                   
                                                                           
                                                        
                                                                       
                                        
                                                  
                                                   
                                                                      
                                                                  
                                                            
                                                               
                                                  
                                                                        
                                                          
                                                      
                                                            
                                                        
                                                       
                                              
                                                  
                                                                                
                                           
                                                                             
                                                                          
                                                                               
                                                                     
                                                             
                                                          
                                                          
export const ACTION_EVENT_KINDS: ReadonlySet<string> = new Set<string>(['stun', 'statusChange', 'grantBuff', 'empower', 'attach', 'detach'])                                                                  

                         
export function eventDidHappen(kind: string, before: unknown, after: unknown): boolean {
  if (!ACTION_EVENT_KINDS.has(kind)) return true                   
  return before !== after
}
